version: "3.8"
services:
  backend:
    build: .
    container_name: dot-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    volumes:
      - ./medusa_pg_db:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - 6379
